name: 'dbt_project'
version: '1.0.0'
config-version: 2

profile: 'retail_project'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  dbt_project:
    staging:
      +materialized: view
      +schema: STAGING_DATA
    analytics:
      +materialized: table
      +schema: Analytics  
 


